#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.3.1}

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template|bash -s - magento-2
bin/download $VERSION

#echo "Your system password has been requested to add an entry to /etc/hosts..."
#echo "127.0.0.1 $DOMAIN" | sudo tee -a /etc/hosts

echo "127.0.0.1 $DOMAIN >> /etc/hosts   , or use localhost:customport as domain name"
bin/setup $DOMAIN
